### ISSUE TITLE
Block Edit Button is very hidden

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/WebApps#22]
When changing the size of a block the edit button is very hard to find and sometimes impossible. 

Request. Can the edit button be replaced with a (i) and put in the top left hand corner. 
Two options
1. For users without permissions they get a popup about Webapps
2. Shows access denied or request access to this block. 

It's just something our users struggle with most with editing blocks.

**Comment by RobTrehy** [comment]
I will make the location configurable in the settings

- Top Left
- Top Right
- Bottom Left
- Bottom right
- Hidden

Clicking the icon will popup a window explaining it is a WebApps Block, with a link to edit the Block.
That page will either allow the user to edit the Block or tell them they are not authorised.

Requesting edit access(/sharing a Block with other users) is a feature I'd like to add in the future
