### ISSUE TITLE
Unable to access buttons and go back if the Weblinks are too long

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/WebApps#52]
When viewing a long list on the Useful List block. This list goes off the bottom of the page and can't be viewed. Refreshing the page also doesn't clear and stays on top. 
This is when you preview the block.

**Comment by RobTrehy** [comment]
I suspect I understand what you're saying, but are you able to provide a screenshot?

**Comment by lehsaclarkson** [comment]
![Screenshot 2022-05-10 155109](https://user-images.githubusercontent.com/12826304/167657686-9c2ac16e-6e98-44d4-9f4b-8095e6664cce.png)
Here is the screenshot

**Comment by RobTrehy** [comment]
Not quite what I thought - but understand the issue, will take a look into it

**Comment by RobTrehy** [comment]
This will not be an issue with the revised UI in WebApps v1.1.0 when released
