### ISSUE TITLE
Incorrect update count displayed on Sidebar/Apps & Plugins DrawerItem

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/WebApps#58]
After the latest release of WebApps it is currently showing the following screenshot

![image](https://user-images.githubusercontent.com/12826304/168295187-189fc1fb-5503-496e-ba67-8fa8df2e4225.png)

I have updated the Staff Directory

**Comment by RobTrehy** [comment]
This has been resolved in v1.1.0

**Comment by RobTrehy** [comment]
A workaround in the meantime, if you wish is to go to Settings > Config Editor (advanced) > I understand
Locate the key `core.available.uodates` and set the value to `[]`

**Comment by lehsaclarkson** [comment]
This works but the webapps Settings stays red with a Zero. This might be correct.
________________________________

**Comment by RobTrehy** [comment]
This issue still exists in v1.1.0

The workaround listed above does still work after updating the Apps/Plugins
